inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs

# Naming/VariableName:  
#   EnforcedStyle: camelCase 

Metrics/BlockLength:
  Max: 50

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength: 
  Max: 20

Metrics/AbcSize:
  Enabled: false    

Naming/MethodName:
  EnforcedStyle: camelCase 

Style/AsciiComments:
  Enabled: No  

Style/GlobalVars:
  AllowedVariables: [
    '$grupo',
    '$descricao',
    '$descricaoFiltro',
    '$codigo' 
    ]
