inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 20  

Style/GlobalVars:
  AllowedVariables:
    - grupo
    - descricao
    - descricaoFiltro