#Origem que serão baixadas as gems
source "http://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'capybara'
gem 'capybara-selenium'
gem 'chromedriver-helper'
gem 'cucumber'
gem 'faker'
gem 'rake'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism', '2.13'